 # Install required plugins
required_plugins = ["vagrant-hostsupdater"]
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|
  config.vm.define "node" do |node|
    node.vm.box = "ubuntu/xenial64"
    node.vm.hostname = "nodeapp"

    node.vm.network :private_network, ip: "192.168.10.100"
    node.hostsupdater.aliases = ["development.local"]
    node.vm.synced_folder "node_app/", "/home/ubuntu/app"
    node.vm.provision "shell", path: "environment/app/provision.sh", privileged: false

    node.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "nodeapp"]
    end
  end


  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "db"
    db.vm.network :private_network, ip: "192.168.56.102"
    db.vm.provision "shell", path: "bootstrap.sh" , privileged: false
    db.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "db"]
    end
  end
end
